# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-01 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antonymapp', '0002_wordpair'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='word_index',
            field=models.IntegerField(default=0),
        ),
    ]
