# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-18 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antonymapp', '0004_auto_20160418_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordpair1',
            name='word_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wordpair2',
            name='word_number',
            field=models.IntegerField(default=0),
        ),
    ]
